openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
  description: API for managing notes
paths:
  /notes:
    get:
      summary: Get all notes
      responses:
        '200':
          description: A list of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    text:
                      type: string
  /notes/{name}:
    get:
      summary: Get a note by name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Note content
        '404':
          description: Note not found
    put:
      summary: Update a note
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Note updated
        '404':
          description: Note not found
    delete:
      summary: Delete a note
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Note deleted
        '404':
          description: Note not found
  /write:
    post:
      summary: Create a new note
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                note_name:
                  type: string
                note:
                  type: string
      responses:
        '201':
          description: Note created
        '400':
          description: Note already exists or missing data
  /UploadForm.html:
    get:
      summary: Get upload form
      responses:
        '200':
          description: HTML upload form
          content:
            text/html:
              schema:
                type: string
